version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  test:
    image: olatundji/testset-docker
    depends_on:
      - chrome
    environment:
      - HUB_HOST=hub
      - CUCUMBER_FEATURES="classpath:resources/features"
      - FILE=resources/test.properties
    volumes:
      - ./output/test-result:/usr/share/test-automation/test-report